package models;
// Generated Mar 17, 2019 11:08:27 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String nombre;
     @JsonIgnore
     private Set locals = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria, String nombre) {
        this.idCategoria = idCategoria;
        this.nombre = nombre;
    }
    public Categoria(int idCategoria, String nombre, Set locals) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
       this.locals = locals;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLocals() {
        return this.locals;
    }
    
    public void setLocals(Set locals) {
        this.locals = locals;
    }


    @Override
    public String toString() {
        return "Categoria{ id='" + idCategoria +", nombre='" + nombre +"}";
    }

}


