package models;
// Generated Mar 17, 2019 11:08:27 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HorarioExcepcion generated by hbm2java
 */
public class HorarioExcepcion  implements java.io.Serializable {


     private int idHorarioExcepcion;
     private Sucursal sucursal;
     private Date fecha;
     private Date horaApertura;
     private Date horaCierre;

    public HorarioExcepcion() {
    }

    public HorarioExcepcion(int idHorarioExcepcion, Sucursal sucursal, Date fecha, Date horaApertura, Date horaCierre) {
       this.idHorarioExcepcion = idHorarioExcepcion;
       this.sucursal = sucursal;
       this.fecha = fecha;
       this.horaApertura = horaApertura;
       this.horaCierre = horaCierre;
    }
   
    public int getIdHorarioExcepcion() {
        return this.idHorarioExcepcion;
    }
    
    public void setIdHorarioExcepcion(int idHorarioExcepcion) {
        this.idHorarioExcepcion = idHorarioExcepcion;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraApertura() {
        return this.horaApertura;
    }
    
    public void setHoraApertura(Date horaApertura) {
        this.horaApertura = horaApertura;
    }
    public Date getHoraCierre() {
        return this.horaCierre;
    }
    
    public void setHoraCierre(Date horaCierre) {
        this.horaCierre = horaCierre;
    }




}


