package models;
// Generated Apr 1, 2019 9:07:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private int idLocal;
     private String nombre;
     private String descripcion;
     private Sucursal sucursal;
     private Set categorias = new HashSet(0);
     private Set personas = new HashSet(0);

    public Local() {
    }

	
    public Local(int idLocal, String nombre) {
        this.idLocal = idLocal;
        this.nombre = nombre;
    }
    public Local(int idLocal, String nombre, String descripcion, Sucursal sucursal, Set categorias, Set personas) {
       this.idLocal = idLocal;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.sucursal = sucursal;
       this.categorias = categorias;
       this.personas = personas;
    }
   
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


