package models;
// Generated Mar 17, 2019 11:08:27 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    @Expose
    private int idPersona;
    private Local local;
    @Expose
    private String nombre;
    @Expose
    private String apellido;
    private String numeroDocumento;
    private Date fechaNacimiento;
    private String email;
    private String usuario;
    private String flagEmpleado;
    private Set personaSucursalServicios = new HashSet(0);
    private Set reservasForIdEmpleado = new HashSet(0);
    private Set reservasForIdCliente = new HashSet(0);

    public Persona() {
    }

    public Persona(int idPersona, Local local, String nombre, String apellido, String email, String flagEmpleado) {
        this.idPersona = idPersona;
        this.local = local;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.flagEmpleado = flagEmpleado;
    }

    public Persona(int idPersona, Local local, String nombre, String apellido, String numeroDocumento, Date fechaNacimiento, String email, String usuario, String flagEmpleado, Set personaSucursalServicios, Set reservasForIdEmpleado, Set reservasForIdCliente) {
        this.idPersona = idPersona;
        this.local = local;
        this.nombre = nombre;
        this.apellido = apellido;
        this.numeroDocumento = numeroDocumento;
        this.fechaNacimiento = fechaNacimiento;
        this.email = email;
        this.usuario = usuario;
        this.flagEmpleado = flagEmpleado;
        this.personaSucursalServicios = personaSucursalServicios;
        this.reservasForIdEmpleado = reservasForIdEmpleado;
        this.reservasForIdCliente = reservasForIdCliente;
    }

    public int getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    public Local getLocal() {
        return this.local;
    }

    public void setLocal(Local local) {
        this.local = local;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }

    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getFlagEmpleado() {
        return this.flagEmpleado;
    }

    public void setFlagEmpleado(String flagEmpleado) {
        this.flagEmpleado = flagEmpleado;
    }

    public Set getPersonaSucursalServicios() {
        return this.personaSucursalServicios;
    }

    public void setPersonaSucursalServicios(Set personaSucursalServicios) {
        this.personaSucursalServicios = personaSucursalServicios;
    }

    public Set getReservasForIdEmpleado() {
        return this.reservasForIdEmpleado;
    }

    public void setReservasForIdEmpleado(Set reservasForIdEmpleado) {
        this.reservasForIdEmpleado = reservasForIdEmpleado;
    }

    public Set getReservasForIdCliente() {
        return this.reservasForIdCliente;
    }

    public void setReservasForIdCliente(Set reservasForIdCliente) {
        this.reservasForIdCliente = reservasForIdCliente;
    }

}
