package models;
// Generated Apr 1, 2019 9:07:39 AM by Hibernate Tools 4.3.1


import com.google.gson.annotations.Expose;
import java.math.BigDecimal;

/**
 * PersonaSucursalServicio generated by hbm2java
 */
public class PersonaSucursalServicio  implements java.io.Serializable {


     private int idPersonaSucursalServicio;
     @Expose
     private Persona persona;
     private SucursalServicio sucursalServicio;
     private BigDecimal precio;

    public PersonaSucursalServicio() {
    }

	
    public PersonaSucursalServicio(int idPersonaSucursalServicio, Persona persona, SucursalServicio sucursalServicio) {
        this.idPersonaSucursalServicio = idPersonaSucursalServicio;
        this.persona = persona;
        this.sucursalServicio = sucursalServicio;
    }
    public PersonaSucursalServicio(int idPersonaSucursalServicio, Persona persona, SucursalServicio sucursalServicio, BigDecimal precio) {
       this.idPersonaSucursalServicio = idPersonaSucursalServicio;
       this.persona = persona;
       this.sucursalServicio = sucursalServicio;
       this.precio = precio;
    }
   
    public int getIdPersonaSucursalServicio() {
        return this.idPersonaSucursalServicio;
    }
    
    public void setIdPersonaSucursalServicio(int idPersonaSucursalServicio) {
        this.idPersonaSucursalServicio = idPersonaSucursalServicio;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public SucursalServicio getSucursalServicio() {
        return this.sucursalServicio;
    }
    
    public void setSucursalServicio(SucursalServicio sucursalServicio) {
        this.sucursalServicio = sucursalServicio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


