package models;
// Generated Apr 1, 2019 9:07:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int idSucursal;
     private Ciudad ciudad;
     private Local local;
     private Mapa mapa;
     private String nombre;
     private String descripcion;
     private int idLocal;
     private Date lunesHoraApertura;
     private Date lunesHoraCierre;
     private Date martesHoraApertura;
     private Date martesHoraCierre;
     private Date miercolesHoraApertura;
     private Date miercolesHoraCierre;
     private Date juevesHoraApertura;
     private Date juevesHoraCierre;
     private Date viernesHoraApertura;
     private Date viernesHoraCierre;
     private Date sabadoHoraApertura;
     private Date sabadoHoraCierre;
     private Date domingoHoraApertura;
     private Date domingoHoraCierre;
     private Set horarioExcepcions = new HashSet(0);
     private Set sucursalServicios = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(Ciudad ciudad, Local local, Mapa mapa, String nombre, int idLocal) {
        this.ciudad = ciudad;
        this.local = local;
        this.mapa = mapa;
        this.nombre = nombre;
        this.idLocal = idLocal;
    }
    public Sucursal(Ciudad ciudad, Local local, Mapa mapa, String nombre, String descripcion, int idLocal, Date lunesHoraApertura, Date lunesHoraCierre, Date martesHoraApertura, Date martesHoraCierre, Date miercolesHoraApertura, Date miercolesHoraCierre, Date juevesHoraApertura, Date juevesHoraCierre, Date viernesHoraApertura, Date viernesHoraCierre, Date sabadoHoraApertura, Date sabadoHoraCierre, Date domingoHoraApertura, Date domingoHoraCierre, Set horarioExcepcions, Set sucursalServicios) {
       this.ciudad = ciudad;
       this.local = local;
       this.mapa = mapa;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.idLocal = idLocal;
       this.lunesHoraApertura = lunesHoraApertura;
       this.lunesHoraCierre = lunesHoraCierre;
       this.martesHoraApertura = martesHoraApertura;
       this.martesHoraCierre = martesHoraCierre;
       this.miercolesHoraApertura = miercolesHoraApertura;
       this.miercolesHoraCierre = miercolesHoraCierre;
       this.juevesHoraApertura = juevesHoraApertura;
       this.juevesHoraCierre = juevesHoraCierre;
       this.viernesHoraApertura = viernesHoraApertura;
       this.viernesHoraCierre = viernesHoraCierre;
       this.sabadoHoraApertura = sabadoHoraApertura;
       this.sabadoHoraCierre = sabadoHoraCierre;
       this.domingoHoraApertura = domingoHoraApertura;
       this.domingoHoraCierre = domingoHoraCierre;
       this.horarioExcepcions = horarioExcepcions;
       this.sucursalServicios = sucursalServicios;
    }
   
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }
    public Mapa getMapa() {
        return this.mapa;
    }
    
    public void setMapa(Mapa mapa) {
        this.mapa = mapa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }
    public Date getLunesHoraApertura() {
        return this.lunesHoraApertura;
    }
    
    public void setLunesHoraApertura(Date lunesHoraApertura) {
        this.lunesHoraApertura = lunesHoraApertura;
    }
    public Date getLunesHoraCierre() {
        return this.lunesHoraCierre;
    }
    
    public void setLunesHoraCierre(Date lunesHoraCierre) {
        this.lunesHoraCierre = lunesHoraCierre;
    }
    public Date getMartesHoraApertura() {
        return this.martesHoraApertura;
    }
    
    public void setMartesHoraApertura(Date martesHoraApertura) {
        this.martesHoraApertura = martesHoraApertura;
    }
    public Date getMartesHoraCierre() {
        return this.martesHoraCierre;
    }
    
    public void setMartesHoraCierre(Date martesHoraCierre) {
        this.martesHoraCierre = martesHoraCierre;
    }
    public Date getMiercolesHoraApertura() {
        return this.miercolesHoraApertura;
    }
    
    public void setMiercolesHoraApertura(Date miercolesHoraApertura) {
        this.miercolesHoraApertura = miercolesHoraApertura;
    }
    public Date getMiercolesHoraCierre() {
        return this.miercolesHoraCierre;
    }
    
    public void setMiercolesHoraCierre(Date miercolesHoraCierre) {
        this.miercolesHoraCierre = miercolesHoraCierre;
    }
    public Date getJuevesHoraApertura() {
        return this.juevesHoraApertura;
    }
    
    public void setJuevesHoraApertura(Date juevesHoraApertura) {
        this.juevesHoraApertura = juevesHoraApertura;
    }
    public Date getJuevesHoraCierre() {
        return this.juevesHoraCierre;
    }
    
    public void setJuevesHoraCierre(Date juevesHoraCierre) {
        this.juevesHoraCierre = juevesHoraCierre;
    }
    public Date getViernesHoraApertura() {
        return this.viernesHoraApertura;
    }
    
    public void setViernesHoraApertura(Date viernesHoraApertura) {
        this.viernesHoraApertura = viernesHoraApertura;
    }
    public Date getViernesHoraCierre() {
        return this.viernesHoraCierre;
    }
    
    public void setViernesHoraCierre(Date viernesHoraCierre) {
        this.viernesHoraCierre = viernesHoraCierre;
    }
    public Date getSabadoHoraApertura() {
        return this.sabadoHoraApertura;
    }
    
    public void setSabadoHoraApertura(Date sabadoHoraApertura) {
        this.sabadoHoraApertura = sabadoHoraApertura;
    }
    public Date getSabadoHoraCierre() {
        return this.sabadoHoraCierre;
    }
    
    public void setSabadoHoraCierre(Date sabadoHoraCierre) {
        this.sabadoHoraCierre = sabadoHoraCierre;
    }
    public Date getDomingoHoraApertura() {
        return this.domingoHoraApertura;
    }
    
    public void setDomingoHoraApertura(Date domingoHoraApertura) {
        this.domingoHoraApertura = domingoHoraApertura;
    }
    public Date getDomingoHoraCierre() {
        return this.domingoHoraCierre;
    }
    
    public void setDomingoHoraCierre(Date domingoHoraCierre) {
        this.domingoHoraCierre = domingoHoraCierre;
    }
    public Set getHorarioExcepcions() {
        return this.horarioExcepcions;
    }
    
    public void setHorarioExcepcions(Set horarioExcepcions) {
        this.horarioExcepcions = horarioExcepcions;
    }
    public Set getSucursalServicios() {
        return this.sucursalServicios;
    }
    
    public void setSucursalServicios(Set sucursalServicios) {
        this.sucursalServicios = sucursalServicios;
    }




}


