package models;
// Generated Mar 17, 2019 11:08:27 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.gson.annotations.Expose;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SucursalServicio generated by hbm2java
 */
public class SucursalServicio  implements java.io.Serializable {

    
     private int idSucursalServicio;
     @Expose
     private Servicio servicio;
       @Expose
     private Sucursal sucursal;
     private Integer duracion;
     private BigDecimal precio;
     private int capacidad;
     @JsonIgnore
     private Set personaSucursalServicios = new HashSet(0);
     @JsonIgnore
     private Set reservas = new HashSet(0);

    public SucursalServicio() {
    }

	
    public SucursalServicio(int idSucursalServicio, Servicio servicio, Sucursal sucursal, BigDecimal precio, int capacidad) {
        this.idSucursalServicio = idSucursalServicio;
        this.servicio = servicio;
        this.sucursal = sucursal;
        this.precio = precio;
        this.capacidad = capacidad;
    }
    public SucursalServicio(int idSucursalServicio, Servicio servicio, Sucursal sucursal, Integer duracion, BigDecimal precio, int capacidad, Set personaSucursalServicios, Set reservas) {
       this.idSucursalServicio = idSucursalServicio;
       this.servicio = servicio;
       this.sucursal = sucursal;
       this.duracion = duracion;
       this.precio = precio;
       this.capacidad = capacidad;
       this.personaSucursalServicios = personaSucursalServicios;
       this.reservas = reservas;
    }
   
    public int getIdSucursalServicio() {
        return this.idSucursalServicio;
    }
    
    public void setIdSucursalServicio(int idSucursalServicio) {
        this.idSucursalServicio = idSucursalServicio;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public Set getPersonaSucursalServicios() {
        return this.personaSucursalServicios;
    }
    
    public void setPersonaSucursalServicios(Set personaSucursalServicios) {
        this.personaSucursalServicios = personaSucursalServicios;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


